mysite/advito/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (
    AnnouncementView, PostDetailView, PostCreateView, EditView, PostDelete, CategoryView, Category_choiseView, IndexView
)
from .urls_auth import urlpatterns as auth_patterns

app_name ='advito'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('announcement/', AnnouncementView.as_view(), name="announcement"),
    path('announcement/<int:post_id>/', PostDetailView.as_view(), name="post_detail"),
    path('announcement/create/', PostCreateView.as_view(), name="post_create"),
    path('announcement/<int:post_id>/edit', EditView.as_view(), name="post_edit"),
    path('announcement/<int:post_id>/delete', PostDelete.as_view(), name="post_delete"),
    path('announcement/<int:post_id>/delete-success', TemplateView.as_view(template_name='advito/delete_success.html'), name="post_delete_success"),
    path('category/', CategoryView.as_view(), name="category"),
    path('category/<int:category_id>/', Category_choiseView.as_view(), name="choise_category")
]

urlpatterns += auth_patterns

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('advito/', include('advito.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/advito/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from .validators import validate_date_edit

# Create your models here.
def user_avatar_path(instance, filename):
    return 'user_{0}/foto/{1}'.format(instance.user.id, filename)

def user_directory_path(instance, filename):
    return 'user_{0}/posts/{1}'.format(instance.author.id, filename)

class Category(models.Model):
    title = models.CharField(max_length=150)
    descriptions = models.CharField(max_length=500)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user', verbose_name='пользователь')
    title = models.CharField(max_length=150, verbose_name='наименование объявления')
    description = models.TextField(max_length=1000, blank=True, verbose_name='содержание объявления')
    image = models.ImageField(upload_to=user_directory_path, verbose_name='фотография товара')
    date_pub = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    date_edit = models.DateTimeField(auto_now=True, verbose_name='дата изменения', validators=[validate_date_edit, ])
    price = models.IntegerField(verbose_name='цена товара')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, related_name='category',
                                 verbose_name='категория товара')

    def __str__(self):
        return self.title

    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return '#'



    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-date_pub', 'title']



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', verbose_name='пользователь')
    about = models.TextField(max_length=1000, verbose_name='о себе')
    avatar = models.ImageField(upload_to=user_avatar_path, blank=True, verbose_name='фото пользователя')
    birth_date = models.DateField(null=True, blank=True, verbose_name='день рождения')
    created = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post, on_delete=models.PROTECT, null=True, blank=True, related_name='post',
        verbose_name='объявления')

    def __str__(self):
        return self.user.username

    def avatar_url(self):
        if self.avatar and hasattr(self.avatar, 'url'):
            return self.avatar.url
        else:
            return '#'

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профели'


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=150)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date_pub = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

mysite/advito/forms.py
from django import forms

from advito.models import Post, Category, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description', 'price', 'image', 'category']

        labels = {
            'title': 'Название',
            'description': 'Описание'
        }

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Название'}),

        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

        widgets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст комментария'}),
        }

mysite/advito/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from advito.models import Post, Category, Comment
from advito.forms import PostForm, CommentForm

from django.db.models import Q

# Create your views here.

class IndexView(ListView):
    model = Post
    template_name = 'advito/index.html'
    context_object_name = 'posts'
    extra_context = {'page_title': '7 last posts'}


    def get_queryset(self):
        search_query = self.request.GET.get('search', '')
        if search_query:
            posts = self.model.objects.filter(
                Q(title__icontains=search_query) | Q(description__icontains=search_query)
            )
        else:
            posts = self.model.objects.all()[:7]
        return posts

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context

# def index(request):
#     posts = Post.objects.all()[:7]
#     return render(request, 'advito/index.html', {'posts': posts, 'page_title': '7 last posts'})

    # return HttpResponse(f'id:{post.id}|title:{post.title}\n' for post in posts)

class AnnouncementView(ListView):
    model = Post
    template_name = 'advito/announcement.html'
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        context = super(AnnouncementView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context


# def announcement(request):
#     posts = Post.objects.all()
#     return render(request, 'advito/announcement.html', {'posts': posts, 'page_title': 'All posts'})
#     # return HttpResponse('announcement')

class PostDetailView(DetailView):
    model = Post
    comment_form = CommentForm
    pk_url_kwarg = "post_id"
    template_name = 'advito/detail.html'


    def get(self, request, post_id, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['categoriy'] = Category.objects.get(category=self.object)
        context['comments'] = Comment.objects.filter(post=self.object).order_by('-date_pub')
        context['comment_form'] = self.comment_form

        return self.render_to_response(context)

    @method_decorator(login_required())
    def post(self, request, post_id, *args, **kwargs):
        post = get_object_or_404(Post, id=post_id)
        form = self.comment_form(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = self.request.user
            comment.post = post
            comment.save()
        return render(request, self.template_name, {
            'post': post,
            # 'comments': Comment.objects.filter(post=self.object).order_by('-date_pub'),
            'comments': post.comment_set.order_by('-date_pub'),
            'comment_form': self.comment_form
        })



# def post_detail(request, post_id):
#     # try:
#     #     post = Post.objects.get(id=post_id)
#     # except: Post.DoesNotExist:
#     #     raise Http404('page not exist')
#     post = get_object_or_404(Post, id=post_id)
#
#     return render(request, 'advito/detail.html', {'post': post, 'page_title': 'Post detail'})


class PostCreateView(LoginRequiredMixin, CreateView):
    form_class = PostForm
    template_name = 'advito/post_create.html'
    login_url = '/advito/login'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(reverse('advito:post_detail', kwargs={'post_id': post.id}))
        else:
            return render(request, 'advito/post_create.html', {
                'form': form})



# class PostCreateView(CreateView):
#     form_class = PostForm
#     template_name = 'advito/post_create.html'
#
#     @method_decorator(login_required(login_url='/admin/login'))
#     def post(self, request, *args, **kwargs):
#         form = self.form_class(request.POST, request.FIELS)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#
#             post.save()
#             return redirect(reverse('advito:post_detail', kwargs={'post_id': post.id}))
#         else:
#             return render(request, 'advito/post_create.html', {'form': form, 'page_title': 'Post create'})

# def post_create(request):
#     form = PostForm()
#
#     if request.method == 'GET':
#         return render(request, 'advito/post_create.html', {'form': form, 'page_title': 'Post create'})
#     elif request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             return redirect(reverse('advito:post_detail', kwargs={'post_id': post.id}))
#         else:
#             return render(request, 'advito/post_create.html', {'form': form, 'page_title': 'Post create'})

class EditView(LoginRequiredMixin, UpdateView):
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = 'advito/post_edit.html'
    form_class = PostForm
    login_url = '/admin/login'

    def get_success_url(self):
        post_id = self.kwargs['post_id']
        return reverse('advito:post_detail', args=(post_id, ))


# def post_edit(request, post_id):
#     return HttpResponse('Post edit')

class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = 'advito/post_delete.html'
    login_url = '/admin/login'
    # success_url = '/advito/'

    def get_success_url(self):
        post_id = self.kwargs['post_id']
        return reverse('advito:post_delete_success', args=(post_id, ))

# def post_delete(request, post_id):
#     return HttpResponse('Post delete')

class CategoryView(ListView):
    model = Category
    context_object_name = 'categorys'
    template_name = 'advito/category.html'
    extra_context = {'page_title': 'All category'}

# def category(request):
#     categorys = Category.objects.all()
#     return render(request, 'advito/category.html', {'categorys': categorys, 'page_title': 'All category'})


class Category_choiseView(DetailView):
    model = Category
    pk_url_kwarg = "category_id"
    template_name = 'advito/category_detail.html'

    def get(self, request, category_id, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['posts'] = Post.objects.filter(category_id=category_id)
        context['category'] = Category.objects.get(id=category_id)
        context['categoris'] = Category.objects.all()


        return self.render_to_response(context)


# def choise_category(request, category_id):
#     posts = Post.objects.filter(category=category_id)
#     category = Category.objects.get(id=category_id)
#     return render(request, 'advito/category_detail.html', {'posts': posts, 'category': category})

mysite/advito/templates/advito/announcement.html
{% extends 'base/base_advito.html' %}
{% block title %}
{{ page_title }}
{% endblock %}
{% block content %}

            <div class="btn-group" role="group" aria-label="Basic outlined example">
                {% for cat in category %}
                <a href="{% url 'advito:choise_category' cat.id %}" class="btn btn-outline-primary">{{ cat.title }}</a>
                {% endfor %}
            </div>
</div>
            {% if posts %}
                {% for post in posts %}
                    <div class="container">
                        <div class="card" style="width: 40rem;">
                            <img src='{{post.image.url}}' alt="{{ post.title }}">
                            <div class="card-body">
                                <p>Товар :
                                    <a href="{% url 'advito:post_detail' post.id %}"> {{ post.title }}</a>
                                </p>
                                <p>Цена : {{ post.price }}</p>
                                <p>Категория : {{ post.category.title }}</p>
                                <p>Продавец :
                                <a href="{% url 'advito:profile' post.author.id %}">{{ post.author.username }}</a>
                                </p>
                                <a href="{% url 'advito:post_detail' post.id %}" class="btn btn-primary">Присмотреться</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
{% endblock content %}

mysite/advito/templates/advito/category.html
{% extends 'base/base_advito.html' %}
{% block title %}
{{ page_title }}
{% endblock %}
{% block content %}
                {% for category in categorys %}
                <ul class="list-group">
                      <li class="list-group-item">
                          <a href="{% url 'advito:choise_category' category.id %}">{{ category.title }}</a>
                          <h3>{{ category.descriptions }}</h3>
                      </li>
                </ul>
                {% endfor %}
{% endblock content %}

mysite/advito/templates/advito/category_detail.html
{% extends 'base/base_advito.html' %}
{% block title %}
{{ page_title }}
{% endblock %}
{% block content %}
        <div class="btn-group" role="group" aria-label="Basic outlined example">
            {% for cat in categoris %}
            <a href="{% url 'advito:choise_category' cat.id %}" class="btn btn-outline-primary">{{ cat.title }}</a>
            {% endfor %}
        </div>
        <h1>{{ category.title }}</h1>

             {% if posts %}
                {% for post in posts %}
                    <div class="container">
                        <div class="card" style="width: 40rem;">
                            <img src='{{post.image.url}}' alt="{{ post.title }}">
                            <div class="card-body">
                                <h5 class="card-title">Товар: {{ post.title }}</h5>
                                <p>Категория :
                                    <a href="{% url 'advito:choise_category' post.category.id %}"> {{ post.category.title }}</a>
                                </p>
                                <p>Продавец :
                                    <a href="{% url 'advito:profile' post.author.id %}">  {{ post.author.username }}</a>
                                </p>
                                <p class="card-text">Немного о товаре : {{ post.description }}</p>
                                <p>Цена : {{ post.price }}</p>
                                <a href="{% url 'advito:post_detail' post.id %}" class="btn btn-primary">Присмотреться</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
{% endblock content %}

mysite/advito/templates/advito/delete_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Post delete</h1>
    <a href="{% url 'advito:index' %}" >На главную</a>
</body>
</html>

mysite/advito/templates/advito/detail.html
{% extends 'base/base_advito.html' %}
{% block title %}
{{ page_title }}
{% endblock %}
{% block content %}
             <div class="container">
                        <div class="card" style="width: 75rem;">
                            <img src='{{post.image.url}}' alt="{{ post.title }}">
                            <div class="card-body">
                                <h5 class="card-title">Товар: {{ post.title }}</h5>
                                <p>Цена : {{ post.price }} руб.</p>
                                <p>Категория :
                                    <a href="{% url 'advito:choise_category' post.category.id %}"> {{ post.category.title }}</a>
                                </p>
                                <p>Продавец :
                                    <a href="{% url 'advito:profile' post.author.id %}">  {{ post.author.username }}</a>
                                </p>
                                <p class="card-text">Немного о товаре : {{ post.description }}</p>

                                <p>Время создания поста: {{ post.date_pub }}</p>

                            </div>
                        </div>
                        <div class="btn-group" role="group" aria-label="Basic outlined example">
                            <a href="{% url 'advito:post_delete' post.id %}" class="btn btn-outline-primary">Удалить Пост</a>
                            <a href="{% url 'advito:post_edit' post.id %}" class="btn btn-outline-primary">Редактировать пост</a>
                        </div>
                        {% if comments %}
                        <h3> Comments: </h3>
                        {% for comment in comments %}
                        <p>{{ comment.author }}</p>
                        <p>{{ comment.text }}</p>
                        {% endfor %}
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            {{ comment_form }}
                            <button type="submit">Добавить коммент</button>
                        </form>
                    </div>

{% endblock content %}

mysite/advito/templates/advito/index.html
{% extends 'base/base_advito.html' %}
{% block title %}
{{ page_title }}
{% endblock %}
{% block content %}
<div class="btn-group" role="group" aria-label="Basic outlined example">
    {% for cat in category %}

    <a href="{% url 'advito:choise_category' cat.id %}" class="btn btn-outline-primary">{{ cat.title }}</a>


    {% endfor %}
</div>
            {% if posts %}
                {% for post in posts %}
                    <div class="container">
                        <div class="card" style="width: 40rem;">
<!--                            <a href="{% url 'advito:post_detail' post.id %}">-->
                                <img src='{{post.image.url}}' alt="{{ post.title }}">
<!--                            </a>-->
                            <div class="card-body">
                                <h5 class="card-title">Товар: {{ post.title }}</h5>
                                <p>Цена : {{ post.price }} руб.</p>
                                <p>Категория :
                                    <a href="{% url 'advito:choise_category' post.category.id %}"> {{ post.category.title }}</a>
                                </p>
                                <p>Продавец :
                                    <a href="{% url 'advito:profile' post.author.id %}">  {{ post.author.username }}</a>
                                </p>
                                <a href="{% url 'advito:post_detail' post.id %}" class="btn btn-primary">Присмотреться</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                Постов нет
            {% endif %}
{% endblock content %}

mysite/advito/templates/advito/post_create.html
{% extends 'base/base_advito.html' %}
{% block title %}
{{ page_title }}
{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for f in form %}
        <p>
        {{ f.label }} {{ f }}
        </p>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Создать пост</button>
    </form>
{% endblock content %}

mysite/advito/templates/advito/post_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if post.author == user %}
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete post</button>
    </form>
    <a href="{% url 'advito:post_detail' post.id %}"> Don`t delete Me </a>
    {% else %}
    <h1>Вы не можжете удалить этот пост</h1>
    {% endif %}
</body>
</html>

mysite/advito/templates/advito/post_edit.html
{% extends 'base/base_advito.html' %}
{% block title %}
{{ page_title }}
{% endblock %}
{% block content %}
    {% if post.author == user %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Обновить пост</button>
    </form>
    <a href="{% url 'advito:post_detail' post.id %}"> Удалить пост</a>
    {% else %}
    <h1>Вы не можете редактировать этот пост</h1>
    {% endif %}
{% endblock content %}